### ISSUE TITLE
UnicodeDecodeError in parse_message when content-type is gzip

### ISSUE THREAD

**Issue by amard33p** [amyangfei/GorMW#13]
```
    payload = binascii.unhexlify(line.strip()).decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 4100: invalid start byte
```
Note that issue is seen even with goreplay's `--prettify-http` flag. Ref: https://github.com/buger/goreplay/issues/400#issuecomment-283675353

**Comment by amyangfei** [comment]
Hi @amard33p , thanks for your feedback!
I have fixed this bug in #16 and #17, after these two PRs either with or without `--prettify-http` works well. Feel free to have another try.
