### ISSUE TITLE
I cant get the http message via the demo

### ISSUE THREAD

**Issue by 2509934810** [amyangfei/GorMW#3]
step 1:
I  use the command to start goplay 
```
gor --input-raw :8000 \
 --output-stdout \
 --output-file request.log \
 --input-raw-track-response \
 --output-http-track-response \
 --prettify-http \
 --output-tcp diferencia:8081 \
 --http-disallow-header 'User-Agent: Gor'
```
step 2:
and use the demo code to start the goplay middleware
                                                                             
```
# coding: utf-8
import sys
from gor.middleware import AsyncioGor


def on_request(proxy, msg, **kwargs):
    proxy.on('response', on_response, idx=msg.id, req=msg)

def on_response(proxy, msg, **kwargs):
    proxy.on('replay', on_replay, idx=kwargs['req'].id, req=kwargs['req'], resp=msg)

def on_replay(proxy, msg, **kwargs):
    replay_status = proxy.http_status(msg.http)
    resp_status = proxy.http_status(kwargs['resp'].http)
    if replay_status != resp_status:
        print('replay status [%s] diffs from response status [%s]\n' % (replay_status, resp_status))
    else:
        print('replay status is same as response status\n')
    sys.stderr.flush()

if __name__ == '__main__':
    proxy = AsyncioGor()
    proxy.on('request', on_request)
    proxy.run()
```
when I send http message to goplay by curl,But I can`t get message from the middleware?

I need help

**Comment by amyangfei** [comment]
Did you start `gor` with the `--middleware ` option, such as `gor --input-raw :80 --middleware "/path/to/middleware_executable" --output-http "http://staging.server"`

**Comment by amyangfei** [comment]
I fixed a bug that `stdin.readline` blocks worker coroutines in https://github.com/amyangfei/GorMW/commit/0b1847e188feca396710dafd7940fa878416ba73, the library works fine now. Feel free to try the latest version
