### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by nlyf** [amyangfei/GorMW#4]
Hello!
I'm trying to use goreplay & middleware while processing pcap. I just simple want to log requests/responses to stderr. I slightly modified your example in readme.
run command:
`gor --input-raw my.pcap:80 -output-http "http://server:8080"  --output-http-track-response --middleware "middleware_gor.py" --input-raw-track-response --input-raw-engine "pcap_file"`
Middleware file is bellow:
```python
# coding: utf-8
import sys
from gor.middleware import AsyncioGor

def log(msg):
    """
    Logging to STDERR as STDOUT and STDIN used for data transfer
    @type msg: str or byte string
    @param msg: Message to log to STDERR
    """
    try:
        msg = str(msg) + '\n'
    except:
        pass
    sys.stderr.write(msg)
    sys.stderr.flush()


def on_request(proxy, msg, **kwargs):
    log("fromtype:1 id: {}".format(msg.id))
    proxy.on('response', on_response, idx=msg.id, req=msg)


def on_response(proxy, msg, **kwargs):
    log("fromtype:2 id: {}".format(msg.id))
    proxy.on('replay', on_replay, idx=kwargs['req'].id, req=kwargs['req'], resp=msg)


def on_replay(proxy, msg, **kwargs):
    log("fromtype:3 id: {}".format(msg.id))
    

if __name__ == '__main__':
    proxy = AsyncioGor()
    proxy.on('request', on_request)
    proxy.run()

```
What am I doing wrong?

**Comment by amyangfei** [comment]
Are you using the latest version `0.2.2`, `0.2.1` has a blocking bug.

**Comment by nlyf** [comment]
Yes, latest, got it from source. Python is 3.5.2 as required

**Comment by amyangfei** [comment]
Strange, I see both `--input-raw my.pcap:80` and `--input-raw-engine "pcap_file"` are provided in gor parameter, have you confirmed whether there is traffic relayed, or is there any errors logged? Besides the middleware file looks fine.

**Comment by nlyf** [comment]
Yes, I'm getting requests (looking at server access.log)
When I do not use  `--input-raw-engine "pcap_file"` option I do not have any traffic.
By the way using example from [goreplay repo](https://github.com/buger/goreplay/blob/master/examples/middleware/echo.py) works fine with both gor options.

**Comment by amyangfei** [comment]
I have no idea, maybe some bugs, could you provide a sample pcap_file to help diagnose?
Btw it works well in my local environment.

**Comment by nlyf** [comment]
Very strange. Using this [pcap file](https://wiki.wireshark.org/SampleCaptures?action=AttachFile&do=get&target=http.cap) i get following output from provided run command:
```
fromtype:1 id: 3dac2ee72baa0e5f3c213d8841f7a6f7fc7d7528
fromtype:1 id: c9c61f29b6266e5d19704773ae139324d7ad62dc
```
I expect to be printed more info. Smth like this:
```
fromtype:3 id: blablablabla
fromtype:3 id: blablablabla
fromtype:2 id: blablablabla
fromtype:2 id: blablablabla
```

**Comment by nlyf** [comment]
I fugured out this problem. That error was with my http server. Middleware & goreplay works fine.
Thanks for fast replies

**Comment by amard33p** [comment]
@nlyf What was the issue in the http server? I am facing the same issue as described here
