### ISSUE TITLE
这个项目目前还会继续维护吗？

### ISSUE THREAD

**Issue by zhangguoqiang666** [amyangfei/GorMW#5]
最近在看goreplay的middleware部分，发现了这个包，感觉还是比较好用的，在使用过程中，我感觉还有一些方法可以提供，现在的获取header，获取查询参数都需要加name参数，作者有考虑过写几个直接返回所有header，所有参数的方法吗，在使用过程中，可能会需要将请求划分为url，params,headers,method这样的部分，所以有一些能够直接将msg解析为通用请求结构的方法会好一点

**Comment by amyangfei** [comment]
获取所有 header 目前可以直接使用 `http_headers`

是希望有一个函数直接返回类似这种结果么
```json
{
  "url": "/?test=123&qwer=ty",
  "paramas": {
    "test": "123",
    "qwer": "ty"
  },
  "header": {
    "Host": "localhost:3000",
    "User-Agent": "Python",
    "Content-Length": 5
  },
  "mehtod": "GET"
}
```

**Comment by zhangguoqiang666** [comment]
我现在想做的第一件事是将http内容解析成您上述的那种格式,但是我在base.py里面没有找到http_headers这个函数，第二个就是我想将msg改写，增加两个字段并发送到其他的应用，然后其他应用再去进行解析，解析出这两个字段和http的具体内容，您觉得这个可以做吗？

**Comment by zhangguoqiang666** [comment]
我pip后安装的版本是release-0.1分支，那个版本的base.py没有http_headers函数，我看了一下，master分支是有的，谢谢，该问题已解决，我接下来试试能不能给msg增加字段并且发送给另一个服务
